apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
spec:
  type: NodePort
  selector:
    app: discover-service
  ports:
  - protocol: TCP
    name: "clientrpc"
    port: 6977
    targetPort: 6977  # client rpc
    nodePort: 30123

