apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: dcache
    discdom: dep1
  name: dcache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcache
  template:
    metadata:
      labels:
        app: dcache
        discdom: dep1
    spec:
      containers:
      - image: dev:7888/app:v9
        name: dcache
        command: ["/usr/local/bin/lua"]
        args: ["/code/dcache.lua"]
        workingDir: "/code"
        ports:
        - containerPort: 8766
        - containerPort: 8767
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8765
          failureThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 20
        startupProbe:
          httpGet:
            path: /startup
            port: 8765
          failureThreshold: 2
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8765
          failureThreshold: 1
          periodSeconds: 5
        volumeMounts:
        - name: host-mount
          mountPath: /code
      volumes:
      - name: host-mount
        hostPath:
          path: /code
          