apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

#commonLabels:
#  app: controller

resources:
- service-primary.yaml
- service-replica.yaml
- deployment-primary.yaml
- deployment-replicas.yaml
#- configMap.yaml