apiVersion: v1
kind: Service
metadata:
  name: replica
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30201
    name: redis
  selector:
    name: redis-replica
