apiVersion: v1
kind: Service
metadata:
  name: primary
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30202
    name: redis
  selector:
    name: redis-primary
    