apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

#commonLabels:
#  app: controller

resources:
- replicaSet.yaml
- service.yaml
- headless.yaml
#- configMap.yaml