apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: controller
  name: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: dev:7888/app:v9
        name: controller
        command: ["/usr/local/bin/lua"]
        args: ["/code/Controller.lua"]
        workingDir: "/code"
        ports:
        - containerPort: 8766  # rpc
        - containerPort: 8767  # web
        - containerPort: 8712  # cli
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8765
          failureThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 20
        startupProbe:
          httpGet:
            path: /startup
            port: 8765
          failureThreshold: 2
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8765
          failureThreshold: 1
          periodSeconds: 5
        volumeMounts:
        - name: host-mount
          mountPath: /code
      volumes:
      - name: host-mount
        hostPath:
          path: /code
