apiVersion: v1
kind: Service
metadata:
  name: controller-svc
spec:
  type: NodePort
  selector:
    app: controller
  ports:
  - protocol: TCP
    name: "rpc"
    port: 8766
    targetPort: 8766  # rpc
    nodePort: 30113
  - protocol: TCP
    name: "cli"
    port: 8712
    targetPort: 8712  # cli
    nodePort: 30112
